CREATE TABLE tickets(
   id                       INTEGER  NOT NULL PRIMARY KEY 
  ,name                     VARCHAR(78) NOT NULL
  ,history_type_id          INTEGER  NOT NULL
  ,ticket_id                INTEGER  NOT NULL
  ,article_id               VARCHAR(7) NOT NULL
  ,type_id                  INTEGER  NOT NULL
  ,queue_id                 INTEGER  NOT NULL
  ,owner_id                 INTEGER  NOT NULL
  ,priority_id              INTEGER  NOT NULL
  ,state_id                 INTEGER  NOT NULL
  ,valid_id                 BIT  NOT NULL
  ,create_time              VARCHAR(19) NOT NULL
  ,create_by                INTEGER  NOT NULL
  ,change_time              VARCHAR(19) NOT NULL
  ,change_by                INTEGER  NOT NULL
  ,id_1                     INTEGER  NOT NULL
  ,name_1                   VARCHAR(33) NOT NULL
  ,comments                 VARCHAR(46)
  ,type_id_1                INTEGER  NOT NULL
  ,valid_id_1               BIT  NOT NULL
  ,create_time_1            VARCHAR(19) NOT NULL
  ,create_by_1              INTEGER  NOT NULL
  ,change_time_1            VARCHAR(19) NOT NULL
  ,change_by_1              INTEGER  NOT NULL
  ,visible_mobile           BIT  NOT NULL
  ,id_2                     INTEGER  NOT NULL
  ,tn                       INTEGER  NOT NULL
  ,title                    VARCHAR(48) NOT NULL
  ,queue_id_1               INTEGER  NOT NULL
  ,ticket_lock_id           BIT  NOT NULL
  ,ticket_answered          BIT  NOT NULL
  ,type_id_2                INTEGER  NOT NULL
  ,service_id               INTEGER  NOT NULL
  ,sla_id                   VARCHAR(4) NOT NULL
  ,user_id                  INTEGER  NOT NULL
  ,responsible_user_id      BIT  NOT NULL
  ,group_id                 BIT  NOT NULL
  ,ticket_priority_id       INTEGER  NOT NULL
  ,ticket_state_id          INTEGER  NOT NULL
  ,group_read               VARCHAR(4) NOT NULL
  ,group_write              VARCHAR(4) NOT NULL
  ,other_read               VARCHAR(4) NOT NULL
  ,other_write              VARCHAR(4) NOT NULL
  ,customer_id              VARCHAR(39) NOT NULL
  ,customer_user_id         VARCHAR(14) NOT NULL
  ,timeout                  INTEGER  NOT NULL
  ,until_time               BIT  NOT NULL
  ,escalation_time          BIT  NOT NULL
  ,escalation_update_time   BIT  NOT NULL
  ,escalation_response_time BIT  NOT NULL
  ,escalation_solution_time BIT  NOT NULL
  ,valid_id_2               BIT  NOT NULL
  ,archive_flag             BIT  NOT NULL
  ,create_time_unix         INTEGER  NOT NULL
  ,create_time_2            VARCHAR(19) NOT NULL
  ,create_by_2              INTEGER  NOT NULL
  ,change_time_2            VARCHAR(19) NOT NULL
  ,change_by_2              INTEGER  NOT NULL
  ,alarm_code               VARCHAR(4) NOT NULL
  ,device_id                VARCHAR(8) NOT NULL
);